function parameters_file = saveParameters(par)
%{ 
    This function creates a dat file with the parameters value of our
  two strain dengue model.
INPUT: par, the parameter vector.
OUTPUT: data fiel with parameters value.
%}
names = ["Lambda_M"; "Lambda_S"; ...
       "Lambda_m1"; "Lambda_m2"; ...
       "beta_M"; "beta_H"; "b"; ...
       "mu_M"; "mu_H"; ...
       "alpha_c"; "alpha_h"; ...   
       "p"; "q"; ...
       "Ms0"; "M10"; "M20"; ... 
       "Is0"; "I10"; "I20"; ...
       "Sm10"; "Sm20"; "Ym10"; ...
       "Ym20"; "Rec0"; "z0"; "w0"; ...
       "h"; "T"];
   
t = datestr(datetime('now'));
t = erase(t, ' ');
file_name = strcat('parameters_', t,'.dat');
parameters_file =fopen(file_name,'w');
fprintf(parameters_file, '%s %f \n', [names par]');
fclose(parameters_file);
